name: Deploy React Frontend to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build React + Vite app
        run: npm run build

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.REACTFRONT_SSH_KEY }}" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem

      - name: Remove old build files on server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key.pem ubuntu@${{ secrets.REACTFRONT_SERVER_IP }} "rm -rf /var/www/html/*"

      - name: Upload new build files
        run: |
          scp -i ~/.ssh/deploy_key.pem -r dist/* ubuntu@${{ secrets.REACTFRONT_SERVER_IP }}:/var/www/html/
